//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 12:25:39 AM CEST 
//


package com.example.vehicle.xmlmodel.location;

import com.example.vehicle.xmlmodel.location.city.City;
import com.example.vehicle.xmlmodel.location.state.State;
import com.example.vehicle.xmlmodel.location.street.Street;

import javax.xml.bind.annotation.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element ref="{http://rentacar.com/state}state"/>
 *         &lt;element ref="{http://rentacar.com/city}city"/>
 *         &lt;element ref="{http://rentacar.com/street}street"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "state",
    "city",
    "street"
})
@XmlRootElement(name = "schemas/location")
public class Location {

    protected Long id;
    @XmlElement(namespace = "http://rentacar.com/state", required = true)
    protected State state;
    @XmlElement(namespace = "http://rentacar.com/city", required = true)
    protected City city;
    @XmlElement(namespace = "http://rentacar.com/street", required = true)
    protected Street street;

    /**
     * Gets the value of the id property.
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link City }
     *     
     */
    public City getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link City }
     *     
     */
    public void setCity(City value) {
        this.city = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link Street }
     *     
     */
    public Street getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link Street }
     *     
     */
    public void setStreet(Street value) {
        this.street = value;
    }

    @Override
    public String toString() {
        return "Location{" +
                "id=" + id +
                ", state=" + state +
                ", city=" + city +
                ", street=" + street +
                '}';
    }

    public com.example.vehicle.dto.location.Location toModel(Location locationXML){

        com.example.vehicle.dto.location.Location locationModel = new com.example.vehicle.dto.location.Location();

        com.example.vehicle.dto.location.State state = new com.example.vehicle.dto.location.State();
        com.example.vehicle.dto.location.City city = new com.example.vehicle.dto.location.City();
        com.example.vehicle.dto.location.Street street = new com.example.vehicle.dto.location.Street();

//        state.setId(locationXML.getState().getId());
//        state.setValue(locationXML.getState().getValue());
//
//        city.setId(locationXML.getCity().getId());
//        city.setValue(locationXML.getCity().getValue());
//
//        street.setId(locationXML.getStreet().getId());
//        street.setValue(locationXML.getStreet().getValue());

        state.setId(null);
        state.setValue(locationXML.getState().getValue());

        city.setId(null);
        city.setValue(locationXML.getCity().getValue());

        street.setId(null);
        street.setValue(locationXML.getStreet().getValue());

        locationModel.setState(state);
        locationModel.setCity(city);
        locationModel.setStreet(street);

        locationModel.setId(null);

        return locationModel;
    }
}
