//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 12:24:22 AM CEST 
//


package com.example.user.xmlmodel.user.user_privilege;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://rentacar.com/user-privilege}userPrivilege"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userPrivilege"
})
@XmlRootElement(name = "getUserPrivilege")
public class GetUserPrivilege {

    @XmlElement(required = true)
    protected UserPrivilege userPrivilege;

    /**
     * Gets the value of the userPrivilege property.
     * 
     * @return
     *     possible object is
     *     {@link UserPrivilege }
     *     
     */
    public UserPrivilege getUserPrivilege() {
        return userPrivilege;
    }

    /**
     * Sets the value of the userPrivilege property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPrivilege }
     *     
     */
    public void setUserPrivilege(UserPrivilege value) {
        this.userPrivilege = value;
    }

}
