//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 02:29:48 AM CEST 
//


package com.example.vehicle.xmlmodel.vehicle;

import com.example.vehicle.xmlmodel.catalogue.vehicle_fuel_type.VehicleFuelType;
import com.example.vehicle.xmlmodel.catalogue.vehicle_make.VehicleMake;
import com.example.vehicle.xmlmodel.catalogue.vehicle_model.VehicleModel;
import com.example.vehicle.xmlmodel.catalogue.vehicle_style.VehicleStyle;
import com.example.vehicle.xmlmodel.catalogue.vehicle_transmission.VehicleTransmission;
import com.example.vehicle.xmlmodel.location.Location;
import com.example.vehicle.xmlmodel.pricelist.Pricelist;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://rentacar.com/vehicle}vehicle"/>
 *         &lt;element name="catalogue">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://rentacar.com/vehicle-fuel-type}vehicleFuelType"/>
 *                   &lt;element ref="{http://rentacar.com/vehicle-make}vehicleMake"/>
 *                   &lt;element ref="{http://rentacar.com/vehicle-model}vehicleModel"/>
 *                   &lt;element ref="{http://rentacar.com/vehicle-style}vehicleStyle"/>
 *                   &lt;element ref="{http://rentacar.com/vehicle-transmission}vehicleTransmission"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://rentacar.com/pricelist}pricelist" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://rentacar.com/location}location"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehicle",
    "catalogue",
    "pricelist",
    "location"
})
@XmlRootElement(name = "createEverythingVehicle")
public class CreateEverythingVehicle {

    @XmlElement(required = true)
    protected Vehicle vehicle;
    @XmlElement(required = true)
    protected Catalogue catalogue;
    @XmlElement(namespace = "http://rentacar.com/pricelist")
    protected List<Pricelist> pricelist;
    @XmlElement(namespace = "http://rentacar.com/location", required = true)
    protected Location location;

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link Vehicle }
     *     
     */
    public Vehicle getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vehicle }
     *     
     */
    public void setVehicle(Vehicle value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the catalogue property.
     * 
     * @return
     *     possible object is
     *     {@link Catalogue }
     *     
     */
    public Catalogue getCatalogue() {
        return catalogue;
    }

    /**
     * Sets the value of the catalogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Catalogue }
     *     
     */
    public void setCatalogue(Catalogue value) {
        this.catalogue = value;
    }

    /**
     * Gets the value of the pricelist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pricelist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPricelist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pricelist }
     * 
     * 
     */
    public List<Pricelist> getPricelist() {
        if (pricelist == null) {
            pricelist = new ArrayList<Pricelist>();
        }
        return this.pricelist;
    }

    public void setPricelist(List<Pricelist> pricelist) {
      this.pricelist = pricelist;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://rentacar.com/vehicle-fuel-type}vehicleFuelType"/>
     *         &lt;element ref="{http://rentacar.com/vehicle-make}vehicleMake"/>
     *         &lt;element ref="{http://rentacar.com/vehicle-model}vehicleModel"/>
     *         &lt;element ref="{http://rentacar.com/vehicle-style}vehicleStyle"/>
     *         &lt;element ref="{http://rentacar.com/vehicle-transmission}vehicleTransmission"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vehicleFuelType",
        "vehicleMake",
        "vehicleModel",
        "vehicleStyle",
        "vehicleTransmission"
    })
    public static class Catalogue {

        @XmlElement(namespace = "http://rentacar.com/vehicle-fuel-type", required = true)
        protected VehicleFuelType vehicleFuelType;
        @XmlElement(namespace = "http://rentacar.com/vehicle-make", required = true)
        protected VehicleMake vehicleMake;
        @XmlElement(namespace = "http://rentacar.com/vehicle-model", required = true)
        protected VehicleModel vehicleModel;
        @XmlElement(namespace = "http://rentacar.com/vehicle-style", required = true)
        protected VehicleStyle vehicleStyle;
        @XmlElement(namespace = "http://rentacar.com/vehicle-transmission", required = true)
        protected VehicleTransmission vehicleTransmission;

        /**
         * Gets the value of the vehicleFuelType property.
         * 
         * @return
         *     possible object is
         *     {@link VehicleFuelType }
         *     
         */
        public VehicleFuelType getVehicleFuelType() {
            return vehicleFuelType;
        }

        /**
         * Sets the value of the vehicleFuelType property.
         * 
         * @param value
         *     allowed object is
         *     {@link VehicleFuelType }
         *     
         */
        public void setVehicleFuelType(VehicleFuelType value) {
            this.vehicleFuelType = value;
        }

        /**
         * Gets the value of the vehicleMake property.
         * 
         * @return
         *     possible object is
         *     {@link VehicleMake }
         *     
         */
        public VehicleMake getVehicleMake() {
            return vehicleMake;
        }

        /**
         * Sets the value of the vehicleMake property.
         * 
         * @param value
         *     allowed object is
         *     {@link VehicleMake }
         *     
         */
        public void setVehicleMake(VehicleMake value) {
            this.vehicleMake = value;
        }

        /**
         * Gets the value of the vehicleModel property.
         * 
         * @return
         *     possible object is
         *     {@link VehicleModel }
         *     
         */
        public VehicleModel getVehicleModel() {
            return vehicleModel;
        }

        /**
         * Sets the value of the vehicleModel property.
         * 
         * @param value
         *     allowed object is
         *     {@link VehicleModel }
         *     
         */
        public void setVehicleModel(VehicleModel value) {
            this.vehicleModel = value;
        }

        /**
         * Gets the value of the vehicleStyle property.
         * 
         * @return
         *     possible object is
         *     {@link VehicleStyle }
         *     
         */
        public VehicleStyle getVehicleStyle() {
            return vehicleStyle;
        }

        /**
         * Sets the value of the vehicleStyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link VehicleStyle }
         *     
         */
        public void setVehicleStyle(VehicleStyle value) {
            this.vehicleStyle = value;
        }

        /**
         * Gets the value of the vehicleTransmission property.
         * 
         * @return
         *     possible object is
         *     {@link VehicleTransmission }
         *     
         */
        public VehicleTransmission getVehicleTransmission() {
            return vehicleTransmission;
        }

        /**
         * Sets the value of the vehicleTransmission property.
         * 
         * @param value
         *     allowed object is
         *     {@link VehicleTransmission }
         *     
         */
        public void setVehicleTransmission(VehicleTransmission value) {
            this.vehicleTransmission = value;
        }

    }

}
