//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 12:26:54 AM CEST 
//


package com.example.vehicle.xmlmodel.catalogue.vehicle_fuel_type;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rentacar.vehicle_fuel_type package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rentacar.vehicle_fuel_type
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetVehicleFuelTypeById }
     * 
     */
    public GetVehicleFuelTypeById createGetVehicleFuelTypeById() {
        return new GetVehicleFuelTypeById();
    }

    /**
     * Create an instance of {@link VehicleFuelType }
     * 
     */
    public VehicleFuelType createVehicleFuelType() {
        return new VehicleFuelType();
    }

    /**
     * Create an instance of {@link GetAllVehicleFuelType }
     * 
     */
    public GetAllVehicleFuelType createGetAllVehicleFuelType() {
        return new GetAllVehicleFuelType();
    }

    /**
     * Create an instance of {@link GetVehicleFuelType }
     * 
     */
    public GetVehicleFuelType createGetVehicleFuelType() {
        return new GetVehicleFuelType();
    }

}
