//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 12:24:49 AM CEST 
//


package com.example.vehicle.xmlmodel.pricelist.vehicle_discount;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://rentacar.com/vehicle-discount}vehicleDiscount"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehicleDiscount"
})
@XmlRootElement(name = "getVehicleDiscount")
public class GetVehicleDiscount {

    @XmlElement(required = true)
    protected VehicleDiscount vehicleDiscount;

    /**
     * Gets the value of the vehicleDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleDiscount }
     *     
     */
    public VehicleDiscount getVehicleDiscount() {
        return vehicleDiscount;
    }

    /**
     * Sets the value of the vehicleDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleDiscount }
     *     
     */
    public void setVehicleDiscount(VehicleDiscount value) {
        this.vehicleDiscount = value;
    }

}
