//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 12:24:49 AM CEST 
//


package com.example.vehicle.xmlmodel.pricelist.vehicle_discount;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rentacar.vehicle_discount package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rentacar.vehicle_discount
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VehicleDiscount }
     * 
     */
    public VehicleDiscount createVehicleDiscount() {
        return new VehicleDiscount();
    }

    /**
     * Create an instance of {@link GetAllVehicleDiscount }
     * 
     */
    public GetAllVehicleDiscount createGetAllVehicleDiscount() {
        return new GetAllVehicleDiscount();
    }

    /**
     * Create an instance of {@link GetVehicleDiscountById }
     * 
     */
    public GetVehicleDiscountById createGetVehicleDiscountById() {
        return new GetVehicleDiscountById();
    }

    /**
     * Create an instance of {@link GetVehicleDiscount }
     * 
     */
    public GetVehicleDiscount createGetVehicleDiscount() {
        return new GetVehicleDiscount();
    }

}
