//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.08 at 04:10:33 AM CEST 
//


package com.example.user.xmlmodel.user.user_details;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user_details_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userDetailsId"
})
@XmlRootElement(name = "getUserDetailsById")
public class GetUserDetailsById {

    @XmlElement(name = "user_details_id")
    protected long userDetailsId;

    /**
     * Gets the value of the userDetailsId property.
     * 
     */
    public long getUserDetailsId() {
        return userDetailsId;
    }

    /**
     * Sets the value of the userDetailsId property.
     * 
     */
    public void setUserDetailsId(long value) {
        this.userDetailsId = value;
    }

}
